-- MealJoy MySQL 8 schema: initial Hostinger deployment foundation.
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) UNIQUE NULL, phone VARCHAR(24) UNIQUE NULL, password_hash VARCHAR(255) NULL, role ENUM('admin','customer','cook','rider') NOT NULL DEFAULT 'customer', status ENUM('active','invited','suspended') NOT NULL DEFAULT 'active', email_verified_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE addresses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, label VARCHAR(50), address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255), city VARCHAR(100) NOT NULL, postcode VARCHAR(20), latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE menu_days (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, menu_date DATE NOT NULL, slot ENUM('lunch','dinner') NOT NULL, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', published_by BIGINT UNSIGNED NULL, published_at TIMESTAMP NULL, UNIQUE KEY unique_menu_day (menu_date,slot), FOREIGN KEY (published_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE menu_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, menu_day_id BIGINT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, description TEXT NULL, dietary_tags JSON NULL, allergens JSON NULL, price DECIMAL(10,2) NULL, is_available BOOLEAN NOT NULL DEFAULT TRUE, sort_order SMALLINT NOT NULL DEFAULT 0, FOREIGN KEY (menu_day_id) REFERENCES menu_days(id) ON DELETE CASCADE);
CREATE TABLE plans (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, meals_per_week TINYINT UNSIGNED NOT NULL, price DECIMAL(10,2) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE subscriptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, plan_id BIGINT UNSIGNED NOT NULL, starts_on DATE NOT NULL, ends_on DATE NULL, status ENUM('active','paused','cancelled','ended') NOT NULL DEFAULT 'active', refundable_deposit DECIMAL(10,2) NOT NULL DEFAULT 600.00, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (plan_id) REFERENCES plans(id));
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, subscription_id BIGINT UNSIGNED NULL, menu_day_id BIGINT UNSIGNED NULL, address_id BIGINT UNSIGNED NOT NULL, rider_id BIGINT UNSIGNED NULL, delivery_date DATE NOT NULL, slot ENUM('lunch','dinner') NOT NULL, quantity SMALLINT UNSIGNED NOT NULL DEFAULT 1, status ENUM('confirmed','preparing','packed','out_for_delivery','delivered','not_received','cancelled') NOT NULL DEFAULT 'confirmed', delivery_otp_hash VARCHAR(255) NULL, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL, FOREIGN KEY (menu_day_id) REFERENCES menu_days(id) ON DELETE SET NULL, FOREIGN KEY (address_id) REFERENCES addresses(id), FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE wallet_ledger (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NULL, amount DECIMAL(10,2) NOT NULL, entry_type ENUM('credit','debit','refund','deposit','deposit_refund','offer') NOT NULL, note VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL);
CREATE TABLE delivery_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, event_type ENUM('picked_up','out_for_delivery','arrived','delivered','delayed','not_received') NOT NULL, reason VARCHAR(255) NULL, latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, evidence_path VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id), FOREIGN KEY (actor_id) REFERENCES users(id));
CREATE TABLE payment_transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NULL, provider ENUM('cashfree','razorpay') NOT NULL, provider_order_id VARCHAR(190) UNIQUE, provider_payment_id VARCHAR(190) UNIQUE NULL, amount DECIMAL(10,2) NOT NULL, status ENUM('created','paid','failed','refunded') NOT NULL DEFAULT 'created', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL);
CREATE TABLE notification_subscriptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, endpoint TEXT NOT NULL, public_key TEXT NOT NULL, auth_secret TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, title VARCHAR(160) NOT NULL, body VARCHAR(500) NOT NULL, kind ENUM('delivery','payment','menu','account','promotion') NOT NULL, read_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
